### ISSUE TITLE
"ERROR: Could not import iRedAdmin settings, check iredadmin_install_path" with iRedMail 0.8.7

### ISSUE THREAD

**Issue by MauJFernandez** [rvojcik/iredmail-cli#1]
I was trying your script and got that error so I went to see what was going on because /usr/share/apache2/iredadmin was OK. I looked in libs/ and found that iredpwd lib is no longer in iRedAdmin libs (I suppose it's now merged in iredutils lib), so removed it and now it works great:

Line 334:

``` try:
    # Import some iRedMail libraries
    import settings
    from libs import iredutils
```

**Comment by rvojcik** [comment]
Hi, there are some differences between iRedAdmin pro and iRedAdmin free.

Which one do you use ?

Could you try to use iredadmin-cli release v0.8.6-1 ?

**Comment by rvojcik** [comment]
Ok I did some tests and create necessary changes. I splited script in two separated versions. Use correct one for you based on which version of iredadmin are you using (pro or free).
