### ISSUE TITLE
Run command without SUDO

### ISSUE THREAD

**Issue by bertalanimre** [rvojcik/iredmail-cli#7]
Is anybody there still? I wish to know how can I run the commands without a root user. With standard user, the command complains about the path (which is correct BTW) while if the same is done with sudo, then it works like a charm.

**Comment by rvojcik** [comment]
Command doesn't need root privileges. 

It operates with iredmail database only. When you run it , it gathers information about database from your iredadmin installation. Maybe your installation has files readable by the root only or another user then you run command.

Your user needs to have correct permissions to access ireadmin installation files.

**Comment by rvojcik** [comment]
When you follow the README, there is 
```
 sudo cp email-manage.py /usr/local/sbin/
```
You have to also change this to 
```
 sudo cp email-manage.py /usr/local/bin/
```

**Comment by bertalanimre** [comment]
Bah, sorry. My bad. :)
